name: Validate issue

on:
  issues:
    types: [edited]

jobs:
  validation:
    if: ${{ github.event.issue.state == 'open' }}
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.2.0
      - name: Install needed packages
        uses: crazy-max/ghaction-chocolatey@v1.2.2
        with:
          args: install trid 7zip.portable -y --no-progress
      - name: Validate Issue
        run: |
          Import-Module "${{ github.workspace }}\scripts\edit.psm1"
          Exclude-package -title "${{ github.event.issue.title }}" -issueNumber ${{ github.event.issue.number }} -repository "${{ github.event.repository.full_name }}"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}